
CREATE TABLE ORDERS.PURCHASE_ORDER_ITEM
(
    ID       VARCHAR(36)   PRIMARY KEY,
    ORDER_ID VARCHAR(36)   NOT NULL,
    SKU      VARCHAR(32)   NOT NULL,
    QUANTITY NUMERIC       NOT NULL,
    PRICE    DECIMAL(9, 2) NOT NULL,
    CREATE_TS TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TS TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
