CREATE TABLE IF NOT EXISTS ORDERS.PURCHASE_ORDER
(
    ID VARCHAR(36) NOT NULL PRIMARY KEY,
    ITEM_COUNT INTEGER,
    CREATE_TS TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TS TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
