---
version: '3.7'

networks:
  default:
    external:
      name: kafka-local

services:

  mysql:
    image: mysql:8.0.21
    hostname: mysql
    container_name: l_mysql
    ports:
      - "3306:3306"
    volumes:
      - ./cnf/local.cnf:/etc/mysql/conf.d/local.cnf
      - ./init.d:/docker-entrypoint-initdb.d
      - ./data:/data
    environment:
      MYSQL_ROOT_PASSWORD: debezium 
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqlpw
